### ISSUE TITLE
Moving or hiding non-ascii characters fail

### ISSUE THREAD

**Issue by vendelin8** [mate-desktop/mozo#26] opened 2016-06-05 06:20 UTC
When I move a menu item elsewhere, or try to hide it, if it has a accented character, the whole application menu disappears.

/usr/lib/python2.7/dist-packages/Mozo/MainWindow.py:86: Warning: Source ID 3535 was not found when attempting to remove it
  GLib.Source.remove(self.timer)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mozo/MainWindow.py", line 430, in on_menu_tree_drag_data_received
    self.editor.copyItem(item, new_parent)
  File "/usr/lib/python2.7/dist-packages/Mozo/MenuEditor.py", line 298, in copyItem
    self.save()
  File "/usr/lib/python2.7/dist-packages/Mozo/MenuEditor.py", line 68, in save
    fd.write(re.sub("\n[\s]*([^\n<]*)\n[\s]*</", "\\1</", getattr(self, menu).dom.toprettyxml().replace('<?xml version="1.0" ?>\n', '')))
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 61, in toprettyxml
    return writer.getvalue()
  File "/usr/lib/python2.7/StringIO.py", line 271, in getvalue
    self.buf += ''.join(self.buflist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 11: ordinal not in range(128)

**Comment by Ryuno-Ki** [comment] 2016-06-10 20:06
The stack trace would be way more readble when put into a [code fence](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

@vendelin8 Which version you are using?

**Comment by vendelin8** [comment] 2016-06-11 06:04
1.14.0-1

**Comment by XRevan86** [comment] 2016-08-22 21:00
Duplicate of #29.

**Closed by XRevan86** 2016-08-22 21:00 UTC
