### ISSUE TITLE
Resetting the mozo menu leaves dummy entries "mozo-created" in the editor

### ISSUE THREAD

**Issue by thorfdbg** [mate-desktop/mozo#8] opened 2013-07-21 14:17 UTC
If I reset the mozo menu by the "reset" button on the bottom of the mozo panel, dummy menu items named "mozo-created" or similar remain. These cannot be deleted, though a second "reset" will trigger their removal.

**Comment by plaguewolf** [comment] 2015-07-23 00:14
same for me on arch linux. wierdness. i also cannot make my own menus, and when i create a menu it apears in Programming under the name of 'mozo-made' and cannot be moved or deleted...

my menus are so ugly, and cannot be moved or deleted, its really messing with my ocd.
what do?

**Comment by monsta** [comment] 2016-08-29 20:05
I can't reproduce this in latest version. Pushing the reset button shows no "mozo-created" items at all.
Do you still get it?

**Comment by monsta** [comment] 2016-11-25 23:54
Well, I guess it's fixed by now then.

**Closed by monsta** 2016-11-25 23:54 UTC
Labels: unconfirmed
